#!/bin/bash

SESSION=$USER
tmux has-session -t $SESSION &> /dev/null

if [ $? != 0 ]
 then
    tmux new-session -d -s $SESSION -n 'Root' 'sudo -s'
    tmux new-window -t $SESSION:2 -n 'Ansible' 'sudo -i -u ansible'
    tmux new-window -t $SESSION:3 -n 'Nagios' 'sudo -i -u nagios'
    tmux new-window -t $SESSION:4 -n 'sdean29@aoede'
    tmux select-window -t $SESSION:1
    tmux -2 attach-session -t $SESSION
fi

tmux attach -t $SESSION
